document.addEventListener('DOMContentLoaded', () => {
  const reduced = matchMedia('(prefers-reduced-motion: reduce)').matches;
  const add = (selector, delay = 90) => document.querySelectorAll(selector).forEach((el, i) => { el.classList.add('products-reveal'); el.style.setProperty('--reveal-delay', `${i * delay}ms`); });
  document.body.classList.add('products-motion-ready');
  document.querySelector('.top-bar')?.classList.add('products-header-enter');
  document.querySelector('.main-header')?.classList.add('products-header-enter');
  const hero = document.querySelector('.product-hero'); hero?.classList.add('hero-motion-ready');
  document.querySelectorAll('.p-hero-copy > .p-kicker, .p-hero-copy > h1, .p-hero-copy > h2, .p-hero-copy > p:not(.p-kicker), .p-hero-copy > .p-btn').forEach((el, i) => el.style.setProperty('--hero-delay', `${180 + i * 110}ms`));
  [['.range > .p-kicker, .range > h2, .range > .lead', 0], ['.product-cards article', 90], ['.p-benefits article', 100], ['.p-showcase .p-wrap > div > .p-kicker, .p-showcase .p-wrap > div > h2, .p-showcase .p-wrap > div > p:not(.p-kicker)', 90], ['.p-showcase li', 80], ['.p-showcase .p-btn, .p-showcase .p-wrap > img', 0], ['.applications > .p-kicker, .applications > h2', 90], ['.application-grid article', 90], ['.p-stats .p-wrap > div', 100], ['.p-cta .p-wrap > div:first-child > *', 90], ['.tube-line img', 100], ['.main-footer .footer-grid > div, .sub-footer', 100]].forEach(([selector, delay]) => add(selector, delay));
  const reveals = document.querySelectorAll('.products-reveal');
  if (reduced || !('IntersectionObserver' in window)) reveals.forEach(el => el.classList.add('is-revealed'));
  else { const observer = new IntersectionObserver((entries, obs) => entries.forEach(entry => { if (entry.isIntersecting) { entry.target.classList.add('is-revealed'); obs.unobserve(entry.target); } }), { threshold: .12, rootMargin: '0px 0px -45px' }); reveals.forEach(el => observer.observe(el)); }
  const stats = document.querySelector('.p-stats'), numberEls = document.querySelectorAll('.p-stats b');
  const count = el => { const target = Number(el.textContent.replace(/\D/g, '')), start = performance.now(); const frame = now => { const p = Math.min((now - start) / 1700, 1); el.textContent = `${Math.round(target * (1 - Math.pow(1 - p, 4)))}+`; if (p < 1) requestAnimationFrame(frame); }; requestAnimationFrame(frame); };
  if (stats && !reduced && 'IntersectionObserver' in window) { const observer = new IntersectionObserver(entries => { if (entries[0].isIntersecting) { numberEls.forEach(count); observer.disconnect(); } }, { threshold: .35 }); observer.observe(stats); }
  const toggle = document.getElementById('mobileToggle'), menu = document.getElementById('navMenu'); toggle?.addEventListener('click', () => { menu?.classList.toggle('active'); const icon = toggle.querySelector('i'); if (icon) icon.className = menu?.classList.contains('active') ? 'fas fa-times' : 'fas fa-bars'; });
  if (!reduced && matchMedia('(hover: hover) and (pointer: fine)').matches) [[hero, document.querySelector('.p-scribble'), 7], [document.querySelector('.p-showcase .p-wrap > img'), document.querySelector('.p-showcase .p-wrap > img'), 6]].forEach(([area, target, amount]) => { if (!area || !target) return; area.addEventListener('pointermove', e => { const r = area.getBoundingClientRect(), x = ((e.clientX - r.left) / r.width - .5) * amount * 2, y = ((e.clientY - r.top) / r.height - .5) * amount * 2; target.style.setProperty('--parallax-x', `${x.toFixed(2)}px`); target.style.setProperty('--parallax-y', `${y.toFixed(2)}px`); target.classList.add('is-parallaxing'); }); area.addEventListener('pointerleave', () => { target.style.setProperty('--parallax-x', '0px'); target.style.setProperty('--parallax-y', '0px'); }); });
});
